"""Where the official words for each committee, subcommittee, committee role, and step of a committee's work are read from
(docs/plan-explain-committees-and-seats.md, phases 1 and 2; docs/source-notes-committees.md says who owns each source and what its terms say).

scripts/fetch_explainers.py reads this table; nothing here is fetched by itself. Each row names a page and two markers (regular expressions):
the passage is the text after the first marker and before the second (scripts/fetch_explainers.py, cut()). A page that changes shape makes
a marker miss, and then the row keeps its last good text (or says "No description on file"), never a guessed passage.

Kinds of row:
  ("rule_x", name)            House Rule X, clause 1: the standing committee "Committee on <name>." and its numbered subjects
  ("rule_xxv", name)          Senate Rule XXV, paragraph 1: "Committee on <name>," and its subjects
  ("manual", start, end, cite)   any passage of the House Rules and Manual (rule text only; the parliamentarian's notes are left out)
  ("senate_rules", start, end, cite)   any passage of the Standing Rules of the Senate
  ("page", key, start, end, cite)      a passage of one of the PAGES below
A subcommittee row is {"url", "start", "end", "what"} (and "flow" when the page breaks lines inside sentences), or {"none": why}.
"""

CONGRESS = 119

# the official sources, registered in scripts/us_sources.py with their terms
SOURCES = {
    "us_house_rules": {
        "name": "Rules of the House of Representatives, One Hundred Nineteenth Congress, in the House Rules and Manual (H. Doc. 118-187)",
        "owner": "U.S. House of Representatives (Parliamentarian), published by the Government Publishing Office on govinfo.gov",
        "url": "https://www.govinfo.gov/content/pkg/CDOC-118hdoc187/html/CDOC-118hdoc187.htm",
        "terms": "govinfo.gov, Public Domain & Copyright Notice: under 17 U.S.C. 105 \"public documents can generally be reprinted without legal restriction\"; customary credit to the originating body. The rules as adopted Jan. 3, 2025 (H. Res. 5); the Rules Committee also posts an updated PDF.",
        "terms_url": "https://www.govinfo.gov/about/policies",
    },
    "us_senate_rules": {
        "name": "Standing Rules of the Senate (Rule XXV, Standing Committees; Rule XXVI, Committee Procedure), as posted by the Senate Committee on Rules and Administration",
        "owner": "U.S. Senate Committee on Rules and Administration",
        "url": "https://www.rules.senate.gov/rules-of-the-senate",
        "terms": "No reuse terms on the site; its privacy policy covers visitor data only. The page cites the Senate Manual (S. Doc. 117-9) on govinfo.gov, a federal work (17 U.S.C. 105). A person should confirm.",
        "terms_url": "https://www.rules.senate.gov/privacy-policy",
    },
    "us_house_resolutions": {
        "name": "House resolutions that set up select committees (H. Res. 11, 118th Congress, applied to the 119th by H. Res. 5; H. Res. 605, 119th Congress)",
        "owner": "U.S. House of Representatives, published by the Government Publishing Office on govinfo.gov",
        "url": "https://www.govinfo.gov/content/pkg/BILLS-119hres5eh/html/BILLS-119hres5eh.htm",
        "terms": "govinfo.gov, Public Domain & Copyright Notice (17 U.S.C. 105).",
        "terms_url": "https://www.govinfo.gov/about/policies",
    },
    "us_code": {
        "name": "United States Code, 2023 edition, on govinfo.gov (15 U.S.C. 1024, the Joint Economic Committee; 26 U.S.C. 8022, the Joint Committee on Taxation)",
        "owner": "Office of the Law Revision Counsel, U.S. House of Representatives, published by the Government Publishing Office",
        "url": "https://www.govinfo.gov/app/collection/uscode",
        "terms": "govinfo.gov, Public Domain & Copyright Notice (17 U.S.C. 105). uscode.house.gov, the Law Revision Counsel's own site, was under maintenance on Oct. 5, 2026.",
        "terms_url": "https://www.govinfo.gov/about/policies",
    },
    "us_committee_pages": {
        "name": "Each committee's own website (an about, jurisdiction, subcommittee, or rules page), and committee rules printed on govinfo.gov",
        "owner": "Each committee of the House, the Senate, or both",
        "url": "https://www.house.gov/committees",
        "terms": "Varies by site (see SITE_TERMS): several House committee sites say their content is a work of the Federal government under 17 U.S.C. 105 and 403; most Senate committee sites state no reuse terms. A person should confirm each.",
        "terms_url": None,
    },
    "us_house_history": {
        "name": "Office of the Historian and Office of Art and Archives, U.S. House of Representatives: glossary and committee fact sheet",
        "owner": "U.S. House of Representatives, Office of the Historian and Office of the Clerk",
        "url": "https://history.house.gov/Education/Lesson-Plans/Glossary/",
        "terms": "history.house.gov states no reuse terms on its privacy page. house.gov's terms of use say \"government-produced materials appearing on this site are not copyright protected.\" A person should confirm they cover history.house.gov.",
        "terms_url": "https://www.house.gov/terms-of-use",
    },
    "us_senate_history": {
        "name": "Senate Historical Office, About the Committee System (Committee Functions, Committee Assignments)",
        "owner": "U.S. Senate, Senate Historical Office (compiled under the Secretary of the Senate)",
        "url": "https://www.senate.gov/about/origins-foundations/committee-system.htm",
        "terms": "No public reuse terms found: the Usage Policy governs Senate offices' use of internet services, and Content Responsibility names the Secretary of the Senate. A federal work (17 U.S.C. 105); a person should confirm.",
        "terms_url": "https://www.senate.gov/general/content_responsibility.htm",
    },
    "us_house_process": {
        "name": "house.gov, The House Explained: The Legislative Process",
        "owner": "U.S. House of Representatives",
        "url": "https://www.house.gov/the-house-explained/the-legislative-process",
        "terms": "house.gov terms of use: \"Pursuant to federal law, government-produced materials appearing on this site are not copyright protected.\"",
        "terms_url": "https://www.house.gov/terms-of-use",
    },
}

# pages read for more than one row (one request each)
PAGES = {
    "hres11": ("us_house_resolutions", "https://www.govinfo.gov/content/pkg/BILLS-118hres11eh/html/BILLS-118hres11eh.htm"),
    "hres605": ("us_house_resolutions", "https://www.govinfo.gov/content/pkg/BILLS-119hres605eh/html/BILLS-119hres605eh.htm"),
    "usc_jec": ("us_code", "https://www.govinfo.gov/content/pkg/USCODE-2023-title15/html/USCODE-2023-title15-chap21-sec1024.htm"),
    "usc_jct": ("us_code", "https://www.govinfo.gov/content/pkg/USCODE-2023-title26/html/USCODE-2023-title26-subtitleG-chap92-sec8022.htm"),
    "indian": ("us_committee_pages", "https://www.indian.senate.gov/about/"),
    "ethics_s": ("us_committee_pages", "https://www.ethics.senate.gov/public/index.cfm/aboutus"),
    "ssci": ("us_committee_pages", "https://www.intelligence.senate.gov/about-the-committee/"),
    "ssci_res": ("us_committee_pages", "https://www.intelligence.senate.gov/about-the-committee/s-res-400/"),
    "aging": ("us_committee_pages", "https://www.aging.senate.gov/about/history"),
    "drug": ("us_committee_pages", "https://www.drugcaucus.senate.gov/about/"),
    "csce": ("us_committee_pages", "https://www.csce.gov/who-we-are/about-commission-security-and-cooperation-europe"),
    "csce_lead": ("us_committee_pages", "https://www.csce.gov/who-we-are/our-structure/leadership"),
    "cha_joint": ("us_committee_pages", "https://cha.house.gov/about/joint-committees"),
    "h_glossary": ("us_house_history", "https://history.house.gov/Education/Lesson-Plans/Glossary/"),
    "s_functions": ("us_senate_history", "https://www.senate.gov/about/origins-foundations/committee-system/committee-functions.htm"),
    "s_assign": ("us_senate_history", "https://www.senate.gov/about/origins-foundations/committee-system/committee-assignments.htm"),
    "h_process": ("us_house_process", "https://www.house.gov/the-house-explained/the-legislative-process"),
}

# the 49 committees, by the record's id (data/us-landscape-2026.json)
COMMITTEES = {
    "HSAG": ("rule_x", "Agriculture"),
    "HSAP": ("rule_x", "Appropriations"),
    "HSAS": ("rule_x", "Armed Services"),
    "HSED": ("rule_x", "Education and Workforce"),
    "HSIF": ("rule_x", "Energy and Commerce"),
    "HSSO": ("rule_x", "Ethics"),
    "HSBA": ("rule_x", "Financial Services"),
    "HSFA": ("rule_x", "Foreign Affairs"),
    "HSHM": ("rule_x", "Homeland Security"),
    "HSHA": ("rule_x", "House Administration"),
    "HSII": ("rule_x", "Natural Resources"),
    "HSGO": ("rule_x", "Oversight and Government Reform"),
    "HSRU": ("rule_x", "Rules"),
    "HSSY": ("rule_x", "Science, Space, and Technology"),
    "HSSM": ("rule_x", "Small Business"),
    "HSPW": ("rule_x", "Transportation and Infrastructure"),
    "HSVR": ("rule_x", "Veterans' Affairs"),
    "HSWM": ("rule_x", "Ways and Means"),
    "HSBU": ("rule_x", "the Budget"),
    "HSJU": ("rule_x", "the Judiciary"),
    "HLIG": ("manual", r"(?=\(b\)\(1\) There shall be referred to the select committee)", r"\n\s*\(2\) Proposed legislation initially reported", "House Rule X, clause 11(b)(1)"),
    "HSZS": ("page", "hres11", r"\(b\) Jurisdiction; Functions\.--\n", r"\n\(c\) Procedure\.--", "H. Res. 11 (118th Congress), section 1(b), which H. Res. 5 (119th Congress), section 4(a), applies in the 119th Congress"),
    "HSQJ": ("page", "hres605", r"\(b\) Investigative Functions and Authority\.--", r"\n\(c\) Procedure\.--", "H. Res. 605 (119th Congress), section 1(b)"),
    "JCSE": ("page", "csce", r"(?=The Commission on Security and Cooperation in Europe, also known as)", r"\n", "Helsinki Commission website, About"),
    "JSLC": ("page", "cha_joint", r"(?=Created on January 26, 1802)", r"\n", "Committee on House Administration website, Joint Committees"),
    "JSPR": ("page", "cha_joint", r"(?=The Joint Committee on Printing, created by)", r"\n", "Committee on House Administration website, Joint Committees"),
    "JSTX": ("page", "usc_jct", r"§8022\. Duties\n", r"\n\(4\) Cross reference", "26 U.S.C. 8022"),
    "JSEC": ("page", "usc_jec", r"\n\(b\) Functions\n", r"\n\(c\) Vacancies", "15 U.S.C. 1024(b)"),
    "SSAF": ("rule_xxv", "Agriculture, Nutrition, and Forestry"),
    "SSAP": ("rule_xxv", "Appropriations"),
    "SSAS": ("rule_xxv", "Armed Services"),
    "SSBK": ("rule_xxv", "Banking, Housing, and Urban Affairs"),
    "SSCM": ("rule_xxv", "Commerce, Science, and Transportation"),
    "SSEG": ("rule_xxv", "Energy and Natural Resources"),
    "SSEV": ("rule_xxv", "Environment and Public Works"),
    "SSFI": ("rule_xxv", "Finance"),
    "SSFR": ("rule_xxv", "Foreign Relations"),
    "SSHR": ("rule_xxv", "Health, Education, Labor, and Pensions"),
    "SSGA": ("rule_xxv", "Governmental Affairs"),
    "SLIA": ("page", "indian", r"(?=The Committee has jurisdiction to study)", r"\n", "Senate Committee on Indian Affairs website, About"),
    "SSRA": ("rule_xxv", "Rules and Administration"),
    "SSSB": ("rule_xxv", "Small Business and Entrepreneurship"),
    "SSVA": ("rule_xxv", "Veterans' Affairs"),
    "SSBU": ("rule_xxv", "the Budget"),
    "SSJU": ("rule_xxv", "the Judiciary"),
    "SLET": ("page", "ethics_s", r"(?=The Committee has three main functions)", r"\n", "Senate Select Committee on Ethics website, About Us"),
    "SLIN": ("page", "ssci", r"(?=Mission: The Committee was created)", r"\n", "Senate Select Committee on Intelligence website, About the Committee"),
    "SPAG": ("page", "aging", r"(?=The Senate Special Committee on Aging was first established)", r"\n(?!Throughout its)", "Senate Special Committee on Aging website, History"),
    "SCNC": ("page", "drug", r"\nPurpose\n", r"\nHistory\n", "Senate Caucus on International Narcotics Control website, About"),
}
# a note shown with a row's official text when the rule itself says something is different from its own wording
COMMITTEE_NOTES = {
    "HSSO": ("manual", r"(?=\(2\) The committee may investigate, subject to paragraph \(b\))", r"\n", "House Rule XI, clause 3(a)(2)"),
    "SSGA": ("senate_rules", r"(?=13 Pursuant to S\. Res\. 445)", r"\n", "Senate Rule XXV, note 13"),
}

# the committee roles. words: the record's own words for the post (every role word in the record must be here)
ROLES = {
    "chair": {"words": ["Chair", "Chairman", "Chairwoman"], "texts": [
        ("page", "h_glossary", r"\nChairman/Chairwoman\n", r"\n", "House Office of the Historian, glossary: Chairman/Chairwoman"),
        ("manual", r"(?=The chair of each standing committee may call and convene)", r"\n\s*\(2\) Three or more members", "House Rule XI, clause 2(c)(1)"),
    ]},
    "ranking": {"words": ["Ranking Member"], "texts": [
        ("page", "h_glossary", r"\nRanking Member\n", r"\n", "House Office of the Historian, glossary: Ranking Member"),
    ]},
    "vice": {"words": ["Vice Chair", "Vice Chairman", "Vice Chairwoman"], "texts": [
        ("manual", r"\(d\) (?=A member of the majority party on each standing committee or)", r"\n\n", "House Rule XI, clause 2(d)"),
        ("page", "ssci_res", r"(?=\(b\) At the beginning of each Congress, the Majority Leader of the Senate shall select a chairman)", r"\n", "S. Res. 400 (94th Congress), section 2(b), on the Senate Select Committee on Intelligence website"),
    ]},
    "exofficio": {"words": ["Ex Officio"], "texts": [
        ("senate_rules", r"(?=\(4\)\(b\)\(3\) Notwithstanding)", r"\n", "Senate Rule XXV, paragraph 4(b)(3)"),
        ("manual", r"(?=\(B\)\(i\) Ex officio service by a chair)", r"\n\s*\(ii\) Service on an investigative", "House Rule X, clause 5(b)(2)(B)(i)"),
    ]},
    "cochair": {"words": ["Cochairman", "Cochair", "Co-Chair", "Cochairwoman"], "texts": [
        ("page", "csce_lead", r"(?=The Helsinki Commission Chairman and Co-Chairman are selected)", r"(?<=or every two years\.)", "Helsinki Commission website, Leadership"),
    ]},
    "member": {"words": ["Member"], "texts": [
        ("manual", r"\(a\)\(1\) (?=The standing committees specified in clause 1 shall be elected)", r"\n\n", "House Rule X, clause 5(a)(1)"),
        ("page", "s_assign", r"(?=Senators are formally elected to standing committees)", r"(?<=which of its members will sit on each committee\.)", "Senate Historical Office, Committee Assignments"),
        ("manual", r"\(h\)\(1\) (?=A measure or recommendation may not be reported)", r"\n\n", "House Rule XI, clause 2(h)(1)"),
    ]},
}

# the five steps of "How a committee works", each with the official words it rests on
PROCESS = {
    "referral": [
        ("manual", r"(?=There shall be in the House the following standing committees)", r"\n\n", "House Rule X, clause 1"),
        ("page", "s_functions", r"(?=The Senate refers approximately)", r"(?<=its committees during each two-year Congress\.)", "Senate Historical Office, Committee Functions"),
    ],
    "hearing": [("page", "s_functions", r"(?=Committees consider hundreds of bills)", r"(?<=and other expert witnesses\.)", "Senate Historical Office, Committee Functions")],
    "markup": [("page", "s_functions", r"(?=At the completion of the hearing process)", r"\n", "Senate Historical Office, Committee Functions")],
    "report": [
        ("manual", r"\(h\)\(1\) (?=A measure or recommendation may not be reported)", r"\n\n", "House Rule XI, clause 2(h)(1)"),
        ("manual", r"2\. \(a\)\(1\) (?=Except as provided in subparagraphs \(2\) and \(3\), all reports of committees)", r"\n\s*\(2\) ", "House Rule XIII, clause 2(a)(1)"),
    ],
    "floor": [("page", "h_process", r"(?=Laws begin as ideas\.)", r"(?<=the bill moves to the Senate\.)", "house.gov, The Legislative Process")],
}

# Each subcommittee, by the record's id: the page that says what it handles, found and read on Oct. 5, 2026 (docs/source-notes-committees.md).
# {"none": why} where no official description could be read as a web page.
SUBCOMMITTEES = {
    'HSAG15': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^Forestry and Horticulture \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAG22': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^Commodity Markets, Digital Assets, and Rural Development \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAG16': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^General Farm Commodities, Risk Management, and Credit \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAG29': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^Livestock, Dairy, and Poultry \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAG14': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^Conservation, Research, and Biotechnology \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAG03': {'url': 'https://agriculture.house.gov/about/rules-and-jurisdiction.htm', 'start': '(?m)^Nutrition and Foreign Agriculture \\([^)\\n]*members[^)\\n]*\\)\\s*[—–-]+\\s*', 'end': '\\n', 'what': 'committee rules page (Rule XI(c), subcommittee jurisdiction)'},
    'HSAP01': {'url': 'https://appropriations.house.gov/subcommittees/agriculture-rural-development-food-and-drug-administration-and-related-agencies/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP19': {'url': 'https://appropriations.house.gov/subcommittees/commerce-justice-science-and-related-agencies-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP02': {'url': 'https://appropriations.house.gov/subcommittees/defense-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP10': {'url': 'https://appropriations.house.gov/subcommittees/energy-and-water-development-and-related-agencies-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP23': {'url': 'https://appropriations.house.gov/subcommittees/financial-services-and-general-government-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP15': {'url': 'https://appropriations.house.gov/subcommittees/homeland-security-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP06': {'url': 'https://appropriations.house.gov/subcommittees/interior-environment-and-related-agencies-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP07': {'url': 'https://appropriations.house.gov/subcommittees/labor-health-and-human-services-education-and-related-agencies/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP24': {'url': 'https://appropriations.house.gov/subcommittees/legislative-branch-0/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP18': {'url': 'https://appropriations.house.gov/subcommittees/military-construction-veterans-affairs-and-related-agencies/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP04': {'url': 'https://appropriations.house.gov/subcommittees/national-security-department-state-and-related-programs/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAP20': {'url': 'https://appropriations.house.gov/subcommittees/transportation-housing-and-urban-development-and-related-agencies/jurisdiction', 'start': '(?m)^Jurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee jurisdiction page (departments and agencies funded)'},
    'HSAS25': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14898', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS02': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14894', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS03': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14895', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS28': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14896', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS29': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14897', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS26': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14893', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSAS35': {'url': 'https://armedservices.house.gov/Issues/Issue/?IssueID=14892', 'start': '(?m)^Jurisdiction:\\s*', 'end': '\\n(?:Subcommittee News|Chairman)\\n', 'what': 'subcommittee page (Jurisdiction paragraph)'},
    'HSED14': {'url': 'https://edworkforce.house.gov/subcommittees/', 'start': '(?m)^Subcommittee on Early Childhood, Elementary, and Secondary Education\\n', 'end': '\\n(?:Subcommittee on |Rep\\. )', 'what': 'subcommittees page (jurisdiction under each heading)'},
    'HSED02': {'url': 'https://edworkforce.house.gov/subcommittees/', 'start': '(?m)^Subcommittee on Health, Employment, Labor, and Pensions\\n', 'end': '\\n(?:Subcommittee on |Rep\\. )', 'what': 'subcommittees page (jurisdiction under each heading)'},
    'HSED13': {'url': 'https://edworkforce.house.gov/subcommittees/', 'start': '(?m)^Subcommittee on Higher Education (?:&|and) Workforce Development\\n', 'end': '\\n(?:Subcommittee on |Rep\\. )', 'what': 'subcommittees page (jurisdiction under each heading)'},
    'HSED10': {'url': 'https://edworkforce.house.gov/subcommittees/', 'start': '(?m)^Subcommittee on Workforce Protections\\n', 'end': '\\n(?:Subcommittee on |Rep\\. )', 'what': 'subcommittees page (jurisdiction under each heading)'},
    'HSIF17': {'url': 'https://energycommerce.house.gov/committees/subcommittee/commerce', 'start': '(?m)^Subcommittee on Commerce, Manufacturing,? and Trade\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSIF16': {'url': 'https://energycommerce.house.gov/committees/subcommittee/communications-technology', 'start': '(?m)^Subcommittee on Communications (?:&|and) Technology\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSIF03': {'url': 'https://energycommerce.house.gov/committees/subcommittee/energy', 'start': '(?m)^Subcommittee on Energy\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSIF14': {'url': 'https://energycommerce.house.gov/committees/subcommittee/health', 'start': '(?m)^Subcommittee on Health\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSIF02': {'url': 'https://energycommerce.house.gov/committees/subcommittee/oversight-investigations', 'start': '(?m)^Subcommittee on Oversight (?:&|and) Investigations\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSIF18': {'url': 'https://energycommerce.house.gov/committees/subcommittee/environment', 'start': '(?m)^Subcommittee on Environment\\n', 'end': '\\n(?:Subcommittees? News|Subcommittee Members)', 'what': 'subcommittee page (jurisdiction paragraph)'},
    'HSBA16': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(A\\) SUBCOMMITTEE ON CAPITAL MARKETS\\.?--', 'end': '\\n\\([A-F]\\) SUBCOMMITTEE ON ', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSBA04': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(C\\) SUBCOMMITTEE ON HOUSING AND INSURANCE\\.?--', 'end': '\\n\\([A-F]\\) SUBCOMMITTEE ON ', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSBA09': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(F\\) SUBCOMMITTEE ON OVERSIGHT AND INVESTIGATIONS\\.?--', 'end': '\\n\\(2\\) In addition, each such subcommittee', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSBA20': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(B\\) SUBCOMMITTEE ON FINANCIAL INSTITUTIONS\\.?--', 'end': '\\n\\([A-F]\\) SUBCOMMITTEE ON ', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSBA21': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(E\\) SUBCOMMITTEE ON DIGITAL ASSETS,\\s+FINANCIAL\\s+TECHNOLOGY,\\s+AND\\s+ARTIFICIAL\\s+INTELLIGENCE\\.?--', 'end': '\\n\\([A-F]\\) SUBCOMMITTEE ON ', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSBA10': {'url': 'https://www.govinfo.gov/content/pkg/CREC-2025-01-23/html/CREC-2025-01-23-pt1-PgH368.htm', 'start': '\\(D\\) SUBCOMMITTEE ON NATIONAL SECURITY,\\s+ILLICIT\\s+FINANCE,\\s+AND\\s+INTERNATIONAL\\s+FINANCIAL\\s+INSTITUTIONS\\.?--', 'end': '\\n\\([A-F]\\) SUBCOMMITTEE ON ', 'what': 'committee rules (Rule 5) as printed in the Congressional Record, govinfo HTML', 'flow': True},
    'HSFA16': {'url': 'https://foreignaffairs.house.gov/subcommittees/africa-subcommittee-119th-congress', 'start': '(?m)^Africa Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:Africa Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA05': {'url': 'https://foreignaffairs.house.gov/subcommittees/east-asia-and-pacific-subcommittee-119th-congress', 'start': '(?m)^East Asia and Pacific Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:East Asia and Pacific Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA14': {'url': 'https://foreignaffairs.house.gov/subcommittees/europe-subcommittee-119th-congress', 'start': '(?m)^Europe Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:Europe Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA13': {'url': 'https://foreignaffairs.house.gov/subcommittees/middle-east-and-north-africa-subcommittee-119th-congress', 'start': '(?m)^Middle East and North Africa Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:Middle East and North Africa Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA07': {'url': 'https://foreignaffairs.house.gov/subcommittees/western-hemisphere-subcommittee-119th-congress', 'start': '(?m)^Western Hemisphere Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:Western Hemisphere Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA17': {'url': 'https://foreignaffairs.house.gov/subcommittees/oversight-and-intelligence-subcommittee-119th-congress', 'start': '(?m)^Oversight and Intelligence Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:Oversight and Intelligence Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSFA19': {'url': 'https://foreignaffairs.house.gov/subcommittees/south-and-central-asia-subcommittee-119th-congress', 'start': '(?m)^South and Central Asia Subcommittee \\(\\d+th Congress\\)\\n', 'end': '\\n(?:South and Central Asia Subcommittee|Chair|Republican Members)\\n', 'what': 'subcommittee page (regional focus and functional jurisdiction)'},
    'HSHM11': {'url': 'https://homeland.house.gov/border-security-facilitation-and-operations/', 'start': '(?m)^Border Security and Enforcement\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHM12': {'url': 'https://homeland.house.gov/emergency-preparedness-response-and-recovery/', 'start': '(?m)^Emergency Management and Technology\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHM08': {'url': 'https://homeland.house.gov/cybersecurity-infrastructure-protection-and-innovation/', 'start': '(?m)^Cybersecurity and Infrastructure Protection\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHM05': {'url': 'https://homeland.house.gov/intelligence-and-counterterrorism/', 'start': '(?m)^Counterterrorism and Intelligence\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHM09': {'url': 'https://homeland.house.gov/oversight-management-and-accountability/', 'start': '(?m)^Oversight, Investigations, and Accountability\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHM07': {'url': 'https://homeland.house.gov/transportation-and-maritime-security/', 'start': '(?m)^Transportation and Maritime Security\\n(?=[^\\n]{80,})', 'end': '\\n(?:Members|Chairman)\\n', 'what': 'subcommittee page (paragraph on what it oversees)'},
    'HSHA08': {'url': 'https://cha.house.gov/about/committee-rules', 'start': '(?m)^Subcommittee on Elections\\n', 'end': '\\n[A-Z][a-z]+ majority party members', 'what': 'committee rules page (Rule 17, subcommittee jurisdiction)'},
    'HSHA27': {'url': 'https://cha.house.gov/subcommittees/modernization-innovation', 'start': '(?m)^Jurisdiction\\n', 'end': '\\n', 'what': 'subcommittee page (Jurisdiction section)'},
    'HSII06': {'url': 'https://naturalresources.house.gov/issues/issue/?IssueID=5062', 'start': '(?m)^Jurisdiction of the Subcommittee:?[ \\t]*\\n', 'end': '\\n(?:(?:Republican |Democratic )?Membership:?|Related News)\\n', 'what': 'subcommittee page (Jurisdiction of the Subcommittee list)'},
    'HSII10': {'url': 'https://naturalresources.house.gov/issues/issue/?IssueID=5063', 'start': '(?m)^Jurisdiction of the Subcommittee:?[ \\t]*\\n', 'end': '\\n(?:(?:Republican |Democratic )?Membership:?|Related News)\\n', 'what': 'subcommittee page (Jurisdiction of the Subcommittee list)'},
    'HSII13': {'url': 'https://naturalresources.house.gov/issues/issue/?IssueID=5937', 'start': '(?m)^Jurisdiction of the Subcommittee:?[ \\t]*\\n', 'end': '\\n(?:(?:Republican |Democratic )?Membership:?|Related News)\\n', 'what': 'subcommittee page (Jurisdiction of the Subcommittee list)'},
    'HSII24': {'url': 'https://naturalresources.house.gov/issues/issue/?IssueID=5066', 'start': '(?m)^Jurisdiction of the Subcommittee:?[ \\t]*\\n', 'end': '\\n(?:(?:Republican |Democratic )?Membership:?|Related News)\\n', 'what': 'subcommittee page (Jurisdiction of the Subcommittee list)'},
    'HSII15': {'url': 'https://naturalresources.house.gov/issues/issue/?IssueID=5064', 'start': '(?m)^Jurisdiction of the Subcommittee:?[ \\t]*\\n', 'end': '\\n(?:(?:Republican |Democratic )?Membership:?|Related News)\\n', 'what': 'subcommittee page (Jurisdiction of the Subcommittee list)'},
    'HSGO24': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Government\\s+Operations,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO06': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+(?:the\\s+)?Military\\s+and\\s+Foreign\\s+Affairs,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO27': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Health\\s+Care\\s+and\\s+Financial\\s+Services,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO05': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Economic\\s+Growth,\\s+Energy\\s+Policy,\\s+and\\s+Regulatory\\s+Affairs,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO12': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Cybersecurity,\\s+Information\\s+Technology,\\s+and\\s+Government\\s+Innovation,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO16': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Delivering\\s+on\\s+Government\\s+Efficiency,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSGO33': {'url': 'https://www.govinfo.gov/content/pkg/CPRT-119HPRT58537/html/CPRT-119HPRT58537.htm', 'start': '\\n\\([A-Z]\\)\\s+(?=Subcommittee\\s+on\\s+Federal\\s+Law\\s+Enforcement,\\s+which\\s+shall)', 'end': '\\n\\((?:[A-Z]|\\d+)\\)\\s', 'what': 'committee rules (Rule 6, subcommittee jurisdiction), GPO committee print 119-2 on govinfo; plain text with hard line breaks', 'flow': True},
    'HSRU02': {'url': 'https://rules.house.gov/about/subcommittees', 'start': '\\nSubcommittee on Legislative and Budget Process\\n', 'end': '\\n(?:Sub ?[Cc]ommittee (?:Chair|Ranking)|Additional Members|Subcommittee on )', 'what': 'subcommittees page (one paragraph per subcommittee)'},
    'HSRU04': {'url': 'https://rules.house.gov/about/subcommittees', 'start': '\\nSubcommittee on Rules and Organization of the House\\n', 'end': '\\n(?:Sub ?[Cc]ommittee (?:Chair|Ranking)|Additional Members|Subcommittee on )', 'what': 'subcommittees page (one paragraph per subcommittee)'},
    'HSSY20': {'url': 'https://science.house.gov/jurisdiction-and-rules', 'start': '\\nSubcommittee on Energy\\n', 'end': '\\n(?:Subcommittee on |Previous Committee Rules|Committee Rules)', 'what': 'jurisdiction and rules page, Subcommittee Jurisdiction section'},
    'HSSY21': {'url': 'https://science.house.gov/jurisdiction-and-rules', 'start': '\\nSubcommittee on Investigations and Oversight\\n', 'end': '\\n(?:Subcommittee on |Previous Committee Rules|Committee Rules)', 'what': 'jurisdiction and rules page, Subcommittee Jurisdiction section'},
    'HSSY16': {'url': 'https://science.house.gov/jurisdiction-and-rules', 'start': '\\nSubcommittee on Space and Aeronautics\\n', 'end': '\\n(?:Subcommittee on |Previous Committee Rules|Committee Rules)', 'what': 'jurisdiction and rules page, Subcommittee Jurisdiction section'},
    'HSSY18': {'url': 'https://science.house.gov/jurisdiction-and-rules', 'start': '\\nSubcommittee on Environment\\n', 'end': '\\n(?:Subcommittee on |Previous Committee Rules|Committee Rules)', 'what': 'jurisdiction and rules page, Subcommittee Jurisdiction section'},
    'HSSY15': {'url': 'https://science.house.gov/jurisdiction-and-rules', 'start': '\\nSubcommittee on Research and Technology\\n', 'end': '\\n(?:Subcommittee on |Previous Committee Rules|Committee Rules)', 'what': 'jurisdiction and rules page, Subcommittee Jurisdiction section'},
    'HSSM23': {'url': 'https://smallbusiness.house.gov/Subcommittees/Subcommittee/?SubcommitteeID=71810', 'start': '\\nJurisdiction ?: ?', 'end': '\\n(?:Website|Facebook|Twitter|Rep\\. |Recent Activity)', 'what': 'subcommittee page, Jurisdiction paragraph'},
    'HSSM24': {'url': 'https://smallbusiness.house.gov/Subcommittees/Subcommittee/?SubcommitteeID=71808', 'start': '\\nJurisdiction ?: ?', 'end': '\\n(?:Website|Facebook|Twitter|Rep\\. |Recent Activity)', 'what': 'subcommittee page, Jurisdiction paragraph'},
    'HSSM27': {'url': 'https://smallbusiness.house.gov/Subcommittees/Subcommittee/?SubcommitteeID=71807', 'start': '\\nJurisdiction ?: ?', 'end': '\\n(?:Website|Facebook|Twitter|Rep\\. |Recent Activity)', 'what': 'subcommittee page, Jurisdiction paragraph'},
    'HSSM21': {'url': 'https://smallbusiness.house.gov/Subcommittees/Subcommittee/?SubcommitteeID=71809', 'start': '\\nJurisdiction ?: ?', 'end': '\\n(?:Website|Facebook|Twitter|Rep\\. |Recent Activity)', 'what': 'subcommittee page, Jurisdiction paragraph'},
    'HSSM22': {'url': 'https://smallbusiness.house.gov/Subcommittees/Subcommittee/?SubcommitteeID=71811', 'start': '\\nJurisdiction ?: ?', 'end': '\\n(?:Website|Facebook|Twitter|Rep\\. |Recent Activity)', 'what': 'subcommittee page, Jurisdiction paragraph'},
    'HSPW05': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107417', 'start': '\\nSubcommittee Jurisdiction:\\n', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, Subcommittee Jurisdiction section with issues and agencies list'},
    'HSPW07': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107418', 'start': '\\nSubcommittee Jurisdiction:\\n', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, Subcommittee Jurisdiction section with issues and agencies list'},
    'HSPW13': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107419', 'start': '\\nSubcommittee Jurisdiction:\\n', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, Subcommittee Jurisdiction section with issues and agencies list'},
    'HSPW12': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107420', 'start': '\\nChair(?:man|woman)?\\n[^\\n]+\\n(?:Subcommittee Jurisdiction:\\n)?', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, responsibility paragraph and issues and agencies list (no Jurisdiction heading on this page)'},
    'HSPW14': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107421', 'start': '\\nSubcommittee Jurisdiction:\\n', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, Subcommittee Jurisdiction section with issues and agencies list'},
    'HSPW02': {'url': 'https://transportation.house.gov/subcommittees/subcommittee/?ID=107422', 'start': '\\nSubcommittee Jurisdiction:\\n', 'end': '\\nRecent Activity:', 'what': 'subcommittee page, Subcommittee Jurisdiction section with issues and agencies list'},
    'HSVR09': {'url': 'https://veterans.house.gov/issues/issue/?IssueID=117990', 'start': '\\n(?=The Subcommittee on Disability Assistance and Memorial Affairs has[^\\n]*jurisdiction)', 'end': '\\n(?:Have a question|Resources for Veterans|Recent Activity|All Related)', 'what': 'subcommittee page, jurisdiction paragraph after the member list'},
    'HSVR10': {'url': 'https://veterans.house.gov/issues/issue/?IssueID=117991', 'start': '\\n(?=The Subcommittee on Economic Opportunity has[^\\n]*jurisdiction)', 'end': '\\n(?:Have a question|Resources for Veterans|Recent Activity|All Related)', 'what': 'subcommittee page, jurisdiction paragraph after the member list'},
    'HSVR03': {'url': 'https://veterans.house.gov/issues/issue/?IssueID=117992', 'start': '\\n(?=The Subcommittee on Health has[^\\n]*jurisdiction)', 'end': '\\n(?:Have a question|Resources for Veterans|Recent Activity|All Related)', 'what': 'subcommittee page, jurisdiction paragraph after the member list'},
    'HSVR08': {'url': 'https://veterans.house.gov/issues/issue/?IssueID=117993', 'start': '\\n(?=The Subcommittee on Oversight and Investigations has[^\\n]*jurisdiction)', 'end': '\\n(?:Have a question|Resources for Veterans|Recent Activity|All Related)', 'what': 'subcommittee page, jurisdiction paragraph after the member list'},
    'HSVR11': {'url': 'https://veterans.house.gov/issues/issue/?IssueID=117997', 'start': '\\n(?=The Subcommittee on Technology Modernization has[^\\n]*jurisdiction)', 'end': '\\n(?:Have a question|Resources for Veterans|Recent Activity|All Related)', 'what': 'subcommittee page, jurisdiction paragraph after the member list'},
    'HSWM02': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nHealth\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSWM03': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nWork (?:&|and) Welfare\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSWM06': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nOversight\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSWM05': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nTax\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSWM01': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nSocial Security\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSWM04': {'url': 'https://waysandmeans.house.gov/subcommittees/', 'start': '\\nSubcommittee On\\nTrade\\n', 'end': '\\n(?:Majority Members|Minority Members|Past Committee Work|What We Are Working On|Subcommittee On)', 'what': 'subcommittees page, jurisdiction paragraph under each subcommittee heading'},
    'HSJU10': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/constitution-and-limited-government-119th-congress', 'start': '\\nThe Subcommittee on the Constitution and Limited Government\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HSJU03': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/courts-intellectual-property-artificial', 'start': '\\nThe Subcommittee on Courts, Intellectual Property, Artificial Intelligence, and the Internet\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HSJU08': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/crime-and-federal-government-surveillance-119th', 'start': '\\nThe Subcommittee on Crime and Federal Government Surveillance\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HSJU01': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/immigration-integrity-security-and-enforcement', 'start': '\\nThe Subcommittee on Immigration Integrity, Security, and Enforcement\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HSJU05': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/antitrust-commercial-and-administrative-law-119th', 'start': '\\nThe Subcommittee on the Administrative State, Regulatory Reform, and Antitrust\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HSJU13': {'url': 'https://judiciary.house.gov/subcommittees/committee-judiciary-119th-congress/oversight-119th-congress', 'start': '\\nThe Subcommittee on Oversight\\n', 'end': '(?: It is chaired|\\nChair\\n|\\nRepublican Members)', 'what': 'subcommittee page, jurisdiction paragraph (chair sentence left out)'},
    'HLIG09': {'url': 'https://intelligence.house.gov/subcommittees/oversight-investigations-subcommittee/', 'start': '\\nOversight (?:&|and) Investigations Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'HLIG01': {'url': 'https://intelligence.house.gov/subcommittees/central-intelligence-agency-subcommittee/', 'start': '\\nCentral Intelligence Agency Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'HLIG02': {'url': 'https://intelligence.house.gov/subcommittees/national-security-agency-cyber-subcommittee/', 'start': '\\nNational Security Agency (?:&|and) Cyber Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'HLIG04': {'url': 'https://intelligence.house.gov/subcommittees/defense-intelligence-overhead-architecture-subcommittee/', 'start': '\\nDefense Intelligence (?:&|and) Overhead Architecture Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'HLIG06': {'url': 'https://intelligence.house.gov/subcommittees/national-intelligence-enterprise-subcommittee/', 'start': '\\nNational Intelligence Enterprise Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'HLIG11': {'url': 'https://intelligence.house.gov/subcommittees/open-source-intelligence-osint-subcommittee/', 'start': '\\nOpen-Source Intelligence \\(OSINT\\) Subcommittee\\n', 'end': '\\n(?:Republicans:|Democrats:)', 'what': 'subcommittee page, legislative and oversight responsibilities paragraph'},
    'SSAF13': {'url': 'https://www.agriculture.senate.gov/about/subcommittees', 'start': 'Subcommittee on Commodities, Derivatives, Risk Management,? and Trade\\n', 'end': '\\n[Cc]hair\\n', 'what': 'committee subcommittees page (oversight summary and related agencies)'},
    'SSAF14': {'url': 'https://www.agriculture.senate.gov/about/subcommittees', 'start': 'Subcommittee on Conservation, Forestry, Natural Resources,? and Biotechnology\\n', 'end': '\\n[Cc]hair\\n', 'what': 'committee subcommittees page (oversight summary and related agencies)'},
    'SSAF15': {'url': 'https://www.agriculture.senate.gov/about/subcommittees', 'start': 'Subcommittee on Rural Development, Energy,? and Credit\\n', 'end': '\\n[Cc]hair\\n', 'what': 'committee subcommittees page (oversight summary and related agencies)'},
    'SSAF16': {'url': 'https://www.agriculture.senate.gov/about/subcommittees', 'start': 'Subcommittee on Food and Nutrition, Specialty Crops, Organics,? and Research\\n', 'end': '\\n[Cc]hair\\n', 'what': 'committee subcommittees page (oversight summary and related agencies)'},
    'SSAF17': {'url': 'https://www.agriculture.senate.gov/about/subcommittees', 'start': 'Subcommittee on Livestock, Dairy, Poultry,? and Food Safety\\n', 'end': '\\n[Cc]hair\\n', 'what': 'committee subcommittees page (oversight summary and related agencies)'},
    'SSAP16': {'url': 'https://www.appropriations.senate.gov/subcommittees/commerce-justice-science-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP22': {'url': 'https://www.appropriations.senate.gov/subcommittees/energy-and-water-development', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP23': {'url': 'https://www.appropriations.senate.gov/subcommittees/financial-services-and-general-government', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP14': {'url': 'https://www.appropriations.senate.gov/subcommittees/homeland-security', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP17': {'url': 'https://www.appropriations.senate.gov/subcommittees/interior-environment-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP18': {'url': 'https://www.appropriations.senate.gov/subcommittees/labor-health-and-human-services-education-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\nAdministration for Children and Families', 'what': 'subcommittee page, Jurisdiction tab (department-level opening lines only; the full agency list is over 4000 characters)'},
    'SSAP19': {'url': 'https://www.appropriations.senate.gov/subcommittees/military-construction-veterans-affairs-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP20': {'url': 'https://www.appropriations.senate.gov/subcommittees/state-foreign-operations-and-related-programs', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP24': {'url': 'https://www.appropriations.senate.gov/subcommittees/transportation-housing-and-urban-development-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP01': {'url': 'https://www.appropriations.senate.gov/subcommittees/agriculture-rural-development-food-and-drug-administration-and-related-agencies', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP02': {'url': 'https://www.appropriations.senate.gov/subcommittees/defense', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAP08': {'url': 'https://www.appropriations.senate.gov/subcommittees/legislative-branch', 'start': '\\nJurisdiction\\n', 'end': '\\Z', 'what': 'subcommittee page, Jurisdiction tab (agencies and accounts funded)'},
    'SSAS14': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nAirland\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS20': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nEmerging Threats and Capabilities\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS17': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nPersonnel\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS15': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nReadiness and Management Support\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS13': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nSeapower\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS16': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nStrategic Forces\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSAS21': {'url': 'https://www.armed-services.senate.gov/subcommittees', 'start': 'Subcommittee on\\nCybersecurity\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (responsibilities and oversight)'},
    'SSBK12': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'Economic Policy\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSBK05': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'National Security and International Trade and Finance\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSBK04': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'Securities, Insurance,? and Investment\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSBK09': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'Housing, Transportation,? and Community Development\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSBK08': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'Financial Institutions and Consumer Protection\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSBK13': {'url': 'https://www.banking.senate.gov/about/subcommittees', 'start': 'Digital Assets\\nJurisdiction\\n', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (jurisdiction list)'},
    'SSCM33': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Aviation, Space,? (&|and) Innovation\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM34': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Telecommunications (&|and) Media\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM35': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Consumer Protection,\\s*Technology,? (&|and) Data Privacy\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM36': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Coast Guard, Maritime,\\s*(&|and) Fisheries\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM37': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Science, Manufacturing,\\s*(&|and) Competitiveness\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM38': {'url': 'https://www.commerce.senate.gov/about/commerce-subcommittees/', 'start': 'Surface Transportation,\\s*Freight, Pipelines,? (&|and) Safety\\n', 'end': '\\nMajority\\b', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSCM39': {'none': "No subcommittee by this name on the committee's subcommittees page (https://www.commerce.senate.gov/about/commerce-subcommittees/, six subcommittees listed), in its HTML rules, or in the senate.gov membership list (https://www.senate.gov/general/committee_membership/committee_memberships_SSCM.htm); tourism, trade, and export matters now appear in the Science, Manufacturing, and Competitiveness description."},
    'SSEG07': {'url': 'https://www.energy.senate.gov/about/subcommittees/', 'start': 'Subcommittee on Water (&|and) Power\\n', 'end': '\\nPhone:', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSEG04': {'url': 'https://www.energy.senate.gov/about/subcommittees/', 'start': 'Subcommittee on National Parks\\n', 'end': '\\nPhone:', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSEG01': {'url': 'https://www.energy.senate.gov/about/subcommittees/', 'start': 'Subcommittee on Energy\\n', 'end': '\\nPhone:', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSEG03': {'url': 'https://www.energy.senate.gov/about/subcommittees/', 'start': 'Subcommittee on Public Lands, Forests,? (&|and) Mining\\n', 'end': '\\nPhone:', 'what': 'committee subcommittees page (jurisdiction paragraph)'},
    'SSEV10': {'url': 'https://www.epw.senate.gov/public/index.cfm/clean-air-climate-and-nuclear-safety', 'start': '\\nJurisdiction\\n', 'end': '\\nMembers\\n', 'what': 'subcommittee page (Jurisdiction list)'},
    'SSEV09': {'url': 'https://www.epw.senate.gov/public/index.cfm/chemical-safety-waste-management-environmental-justice-and-regulatory-oversight', 'start': '\\nJurisdiction\\n', 'end': '\\nMembers\\n', 'what': 'subcommittee page (Jurisdiction list)'},
    'SSEV08': {'url': 'https://www.epw.senate.gov/public/index.cfm/transportation-and-infrastructure', 'start': '\\nJurisdiction\\n', 'end': '\\nMembers\\n', 'what': 'subcommittee page (Jurisdiction list)'},
    'SSEV15': {'url': 'https://www.epw.senate.gov/public/index.cfm/fisheries-water-and-wildlife', 'start': '\\nJurisdiction\\n', 'end': '\\nMembers\\n', 'what': 'subcommittee page (Jurisdiction list)'},
    'SSFI12': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFI10': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFI13': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFI14': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFI11': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFI02': {'none': 'Subcommittee page lists members only (https://www.finance.senate.gov/about/subcommittees); the jurisdiction page (https://www.finance.senate.gov/about/jurisdiction) covers the full committee only; committee rules are only a download (https://www.finance.senate.gov/download/rules-of-the-procedure-119-2).'},
    'SSFR01': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'Europe (&|and) Regional Security Cooperation\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR09': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'Africa (&|and) Global Health Policy\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR02': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'East Asia, [Tt]he Pacific,? (&|and) International Cybersecurity Policy\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR07': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'Near East, South Asia, Central Asia,? (&|and) Counterterrorism\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR06': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'Western Hemisphere, Transnational Crime, Civilian Security, Democracy, Human Rights,? (&|and) Global Women.s Issues\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR15': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'Multilateral International Development, Multilateral Institutions,? (&|and) International Economic, Energy,? (&|and) Environmental Policy\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSFR14': {'url': 'https://www.foreign.senate.gov/about/subcommittees', 'start': 'State Department (&|and) USAID Management, International Operations,? (&|and) Bilateral International Development\\n', 'end': '\\n[Cc]hairman\\n', 'what': 'committee subcommittees page (responsibilities paragraph)'},
    'SSHR11': {'url': 'https://www.help.senate.gov/about/subcommittees', 'start': 'Employment (&|and) Workplace Safety\\n(?:(?!\\nChairman\\n)[\\s\\S])*?(?=The Subcommittee\\s+has jurisdiction)', 'end': '\\nChairman\\n', 'what': 'committee subcommittees page (jurisdiction sentence; the sentence naming the chair and ranking member is skipped)', 'flow': True},
    'SSHR12': {'url': 'https://www.help.senate.gov/about/subcommittees', 'start': 'Primary Health (&|and) Retirement Security\\n(?:(?!\\nChairman\\n)[\\s\\S])*?(?=The Subcommittee\\s+has jurisdiction)', 'end': '\\nChairman\\n', 'what': 'committee subcommittees page (jurisdiction sentence; the sentence naming the chair and ranking member is skipped)', 'flow': True},
    'SSHR09': {'url': 'https://www.help.senate.gov/about/subcommittees', 'start': 'Education (&|and) the American Family\\n(?:(?!\\nChairman\\n)[\\s\\S])*?(?=The Subcommittee\\s+has jurisdiction)', 'end': '\\nChairman\\n', 'what': 'committee subcommittees page (jurisdiction sentence; the sentence naming the chair and ranking member is skipped)', 'flow': True},
    'SSGA01': {'url': 'https://www.hsgac.senate.gov/subcommittees/investigations/', 'start': 'Permanent Subcommittee on\\nInvestigations\\n', 'end': '\\nPSI Historical Background', 'what': 'subcommittee page (opening description)'},
    'SSGA20': {'none': 'Subcommittee page (https://www.hsgac.senate.gov/subcommittees/dmdcc/) shows placeholder Lorem ipsum text and members only; its rules of procedure and the committee jurisdiction text are only in PDFs (https://www.hsgac.senate.gov/wp-content/uploads/Jurisdiction-HSGAC-119th-Congress-1.pdf).'},
    'SSGA22': {'none': 'Subcommittee page (https://www.hsgac.senate.gov/subcommittees/bmfwra/) shows placeholder Lorem ipsum text and members only; its rules of procedure (https://www.hsgac.senate.gov/wp-content/uploads/Rules-119th-Congress-Border-Management-Subcommittee-Rules-of-Procedures.pdf) and the committee jurisdiction text are only in PDFs.'},
    'SSJU21': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nThe Constitution\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)', 'flow': True},
    'SSJU22': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nCrime and Counterterrorism\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)'},
    'SSJU01': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nAntitrust, Competition Policy,? and Consumer Rights\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)'},
    'SSJU04': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nBorder Security and Immigration\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)'},
    'SSJU25': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nFederal Courts, Oversight, Agency Action,? and Federal Rights\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)'},
    'SSJU26': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nIntellectual Property\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)', 'flow': True},
    'SSJU27': {'none': "No subcommittee by this name on the committee's subcommittees page (https://www.judiciary.senate.gov/about/subcommittees, seven subcommittees listed) or in the senate.gov membership list (https://www.senate.gov/general/committee_membership/committee_memberships_SSJU.htm)."},
    'SSJU28': {'url': 'https://www.judiciary.senate.gov/about/subcommittees', 'start': 'Subcommittee on\\nPrivacy, Technology,? and the Law\\nJurisdiction:\\s*', 'end': '\\nMajority Members', 'what': 'committee subcommittees page (Jurisdiction paragraph)'},
}

# What each committee website says about reuse (read Oct. 5, 2026), by committee id; a person confirms these.
SITE_TERMS = {
    'HSAG': {'site': 'https://agriculture.house.gov/', 'terms_url': 'https://agriculture.house.gov/privacy', 'terms': 'No reuse terms found on the pages checked. The footer links only Privacy and Accessibility; the privacy page covers contact information only; /copyright returns 404.', 'checked': '2026-10-05'},
    'HSAP': {'site': 'https://appropriations.house.gov/', 'terms_url': 'https://appropriations.house.gov/privacy', 'terms': 'No reuse terms found on the pages checked. The footer links Privacy and Accessibility; the privacy page covers cookies, Google Analytics, and captcha tools; /copyright returns 404.', 'checked': '2026-10-05'},
    'HSAS': {'site': 'https://armedservices.house.gov/', 'terms_url': 'https://armedservices.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code." (The footer links Privacy and Accessibility; the /copyright page exists but is not linked in the footer.)', 'checked': '2026-10-05'},
    'HSED': {'site': 'https://edworkforce.house.gov/', 'terms_url': 'https://edworkforce.house.gov/privacypolicy', 'terms': 'No reuse terms found on the pages checked. The footer links Privacy Policy and Accessibility; the privacy page covers visit logs and e-mail only; /copyright returns 404. (edlabor.house.gov now serves edworkforce.house.gov.)', 'checked': '2026-10-05'},
    'HSIF': {'site': 'https://energycommerce.house.gov/', 'terms_url': 'https://energycommerce.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code." (The footer links Privacy and Accessibility; the /copyright page exists but is not linked in the footer.)', 'checked': '2026-10-05'},
    'HSBA': {'site': 'https://financialservices.house.gov/', 'terms_url': 'https://www.govinfo.gov/about/policies', 'terms': 'No reuse terms found on the committee site (no privacy or copyright link in the footer; /copyright and /privacy return 404). The subcommittee text is taken from the Congressional Record on govinfo.gov, whose Policies page says: "Copyright protection under this title is not available for any work of the United States Government" (17 U.S.C. 105) and "public documents can generally be reprinted without legal restriction."', 'checked': '2026-10-05'},
    'HSFA': {'site': 'https://foreignaffairs.house.gov/', 'terms_url': 'https://foreignaffairs.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code." The page adds: "If you have any questions about the use or attribution of any content on this website, please contact our Washington DC, Office."', 'checked': '2026-10-05'},
    'HSHM': {'site': 'https://homeland.house.gov/', 'terms_url': None, 'terms': 'No reuse terms found on the pages checked. The footer\'s "copyright" and "privacy" links point back to the current page, and /copyright/ and /privacy/ return 404.', 'checked': '2026-10-05'},
    'HSHA': {'site': 'https://cha.house.gov/', 'terms_url': 'https://cha.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code." The page adds: "If you have any questions about the use or attribution of any content on this website, please contact our Washington DC, Office."', 'checked': '2026-10-05'},
    'HSII': {'site': 'https://naturalresources.house.gov/', 'terms_url': 'https://naturalresources.house.gov/privacy', 'terms': 'No reuse terms found on the pages checked. The footer links only Privacy Policy, which covers visit logs and e-mail lists; /copyright returns 404.', 'checked': '2026-10-05'},
    'HSGO': {'site': 'https://oversight.house.gov/', 'terms_url': None, 'terms': 'Footer: "© 2026 Committee on Oversight and Government Reform". No reuse terms found on the pages checked.', 'checked': '2026-10-05'},
    'HSRU': {'site': 'https://rules.house.gov/', 'terms_url': 'https://rules.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code."', 'checked': '2026-10-05'},
    'HSSY': {'site': 'https://science.house.gov/', 'terms_url': 'https://science.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code."', 'checked': '2026-10-05'},
    'HSSM': {'site': 'https://smallbusiness.house.gov/', 'terms_url': 'https://smallbusiness.house.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked', 'checked': '2026-10-05'},
    'HSPW': {'site': 'https://transportation.house.gov/', 'terms_url': 'https://transportation.house.gov/miscellaneous/privacy-policy.htm', 'terms': 'No reuse terms found on the pages checked', 'checked': '2026-10-05'},
    'HSVR': {'site': 'https://veterans.house.gov/', 'terms_url': 'https://veterans.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code."', 'checked': '2026-10-05'},
    'HSWM': {'site': 'https://waysandmeans.house.gov/', 'terms_url': 'https://waysandmeans.house.gov/privacy-policy-2/', 'terms': 'No reuse terms found on the pages checked', 'checked': '2026-10-05'},
    'HSJU': {'site': 'https://judiciary.house.gov/', 'terms_url': 'https://judiciary.house.gov/copyright', 'terms': '"Except as otherwise noted in this website, all of the content of the website constitutes a work of the Federal government under sections 105 and 403 of title 17 of the U.S. Code."', 'checked': '2026-10-05'},
    'HLIG': {'site': 'https://intelligence.house.gov/', 'terms_url': None, 'terms': 'No reuse terms found on the pages checked', 'checked': '2026-10-05'},
    'SSAF': {'site': 'https://www.agriculture.senate.gov/', 'terms_url': 'https://www.senate.gov/usage/internetpolicy.htm', 'terms': "No reuse terms found on the pages checked (the footer's Privacy Policy link goes to the Senate's Internet usage rules for offices; a Photo Credits page credits home page photos 'Courtesy of the Arkansas Farm Bureau').", 'checked': '2026-10-05'},
    'SSAP': {'site': 'https://www.appropriations.senate.gov/', 'terms_url': 'https://www.appropriations.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSAS': {'site': 'https://www.armed-services.senate.gov/', 'terms_url': 'https://www.armed-services.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSBK': {'site': 'https://www.banking.senate.gov/', 'terms_url': None, 'terms': 'No reuse terms found on the pages checked (no privacy or terms link in the footer; /privacy-policy returns 410 Gone).', 'checked': '2026-10-05'},
    'SSCM': {'site': 'https://www.commerce.senate.gov/', 'terms_url': 'https://www.commerce.senate.gov/privacy-policy/', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers personal information gathered on the site only).', 'checked': '2026-10-05'},
    'SSEG': {'site': 'https://www.energy.senate.gov/', 'terms_url': None, 'terms': 'No reuse terms found on the pages checked (no privacy or terms link in the footer; /privacy-policy returns 404).', 'checked': '2026-10-05'},
    'SSEV': {'site': 'https://www.epw.senate.gov/', 'terms_url': 'https://www.epw.senate.gov/public/index.cfm?p=privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSFI': {'site': 'https://www.finance.senate.gov/', 'terms_url': 'https://www.finance.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSFR': {'site': 'https://www.foreign.senate.gov/', 'terms_url': 'https://www.foreign.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSHR': {'site': 'https://www.help.senate.gov/', 'terms_url': 'https://www.help.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSGA': {'site': 'https://www.hsgac.senate.gov/', 'terms_url': 'https://www.hsgac.senate.gov/privacy-policy/', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
    'SSJU': {'site': 'https://www.judiciary.senate.gov/', 'terms_url': 'https://www.judiciary.senate.gov/privacy-policy', 'terms': 'No reuse terms found on the pages checked (Privacy Policy covers visitor data only).', 'checked': '2026-10-05'},
}
